channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - geos
  - pyproj>=2.6
  - numpy>=1.18.4
  - matplotlib>=3.2.1
  - mpi4py=3.0.3
  - h5py>=2.10.0
  - pip
  - pip:
    - obspy>=1.2.1
    - cartopy>=0.18.0
    - pyyaml
    - sphinx
    - sphinx_rtd_theme
    - pytest
    - py
    - flake8
    - git+https://github.com/wjlei1990/pyflex@merge
    - git+git://github.com/lsawade/pyasdf.git@devel
    - git+git://github.com/lsawade/spaceweight.git@master
    - git+git://github.com/lsawade/pycmt3d.git@devel