name: gcmt3d
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy<=1.16.4
  - matplotlib
  - cartopy
  - mpi4py
  - h5py
  - pip
  - pip:
    - obspy
    - pyyaml
    - sphinx
    - sphinx_rtd_theme
    - pytest
    - py
    - flake8
    - git+https://github.com/wjlei1990/pyflex@merge
    - git+git://github.com/lsawade/pyasdf.git@devel
    - git+git://github.com/lsawade/spaceweight.git@master
    - git+git://github.com/lsawade/pycmt3d.git@devel



